title: Balazs Fabian
description: Programming write-ups and experiments.

remote_theme: pages-themes/midnight@v0.2.0

permalink: /:title/

defaults:
  - scope:
      type: posts
    values:
      layout: post

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - vendor
  - node_modules

plugins:
- jekyll-remote-theme
- jekyll-seo-tag

sass:
  quiet_deps: true
